name: preprocessing

on:
  workflow_dispatch:
  push:
    paths:
      - ./loan_approval_dataset.csv
      - preprocessing/automate_Dewi.py

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: pip install numpy pandas scikit-learn

    - name: Run preprocessing
      run: python preprocessing/automate_Dewi.py

    - name: Commit and push preprocessed files
      run: |
        git config --global user.name ${{ secret.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git add preprocessing/loan__approval_preprocessing/loan_preprocessing.csv preprocessing/loan__approval_preprocessing/scaler_model.joblib
        git commit -m "Auto update preprocessed data"
        git push
